version: '3.8'
services:
  hadith-db:
    container_name: hadith-db
    image: postgres:16
    restart: always
    ports:
      - "54302:5432"
    environment:
      POSTGRES_PASSWORD: hadith
      POSTGRES_USER: hadith
      POSTGRES_DB: hadith
